In [3]:
import numpy as np

In [4]:
a = np.array([[0,0,0],[0,0,0],[0,0,0]])

In [6]:
np.where(a==0)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [7]:
a==0

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])